### PR TITLE
updates to reception descriptions

### PR DESCRIPTION
**Pull request by polarbeardesign**

### CODE REVIEW

**Comment by codersquid** [comment]
@polarbeardesign I'll take care of updating the schedule for this change. I think I'll be able to use the django admin since there are no room changes.

**Comment by codersquid** [comment]
Oh! I forgot about https://conference.scipy.org/scipy2014/schedule/tutorials/edit/ for changing descriptions versus using the django admin. This is a lot easier for changing the labels for special events. I'll have to use the admin for changing slot duration, otoh.

**Comment by codersquid** [comment]
It's updated. People will probably need to do ctl-shift-R a couple of times to flush the cache.

**Comment by polarbeardesign** [comment]
OK - thanks aging for the quick turn-around!

Jim

Jim Ivanoff
www.polarbeardesign.net

**Pull request merged**
